version: '3'

services:
  proxy:
    build: ./proxy
    ports:
      - 1100:80
    volumes:
    - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    - ./proxy/logs/:/var/log/nginx
    - ./proxy/proxy.conf:/etc/nginx/includes/proxy.conf

  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${VOLUME_DB}:/docker-entrypoint-initdb.d
      - volume_papeterie:/var/lib/mysql
    # ports:
    #   - 3306:3306

  api_papeterie:
    build:
      dockerfile: ./API_Papeterie/Dockerfile
      context: ./API
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - App_Authority=${APP_AUTHORITY}
      - App_ClientId=${APP_CLIENTID}
      - App_SwaggerAuthority=${APP_SWAGGERAUTHORITY}
    # ports:
    #   - 2200:8080
    depends_on:
      - db
      - proxy

  webapp: 
    build: ./WebApp_Papeterie
    depends_on:
      - api_papeterie

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_LOG_LEVEL: DEBUG
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: myadminpwd
      KC_PROXY: edge
      KC_PROXY_MODE: edge
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_PATH: /auth
      KC_HOSTNAME_URL: http://localhost:1100/auth
      KC_HOSTNAME_ADMIN_URL: http://localhost:1100/auth
    command:
      - start-dev
    volumes:
      - ./volumes/keycloak:/opt/keycloak/data/h2
    # ports:
    # - 8092:8080

volumes:
  volume_papeterie:
