version: '3'

services:
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: papeterie
      MYSQL_USER: moi
      MYSQL_PASSWORD: moi123
      MYSQL_ROOT_PASSWORD: aaaaaaaa
    volumes:
      - ${VOLUME_DB}:/docker-entrypoint-initdb.d

  webapp:
    build: ./WebApp_Papeterie
    ports:
      - "3333:80"
    depends_on:
      - api

  api:
    build: ./API
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
