version: '3'

services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${VOLUME_DB}:/docker-entrypoint-initdb.d
      - volume_papeterie:/var/lib/mysql
    networks:
      - backend

  api_papeterie:
    build:
      dockerfile: ./API_Papeterie/Dockerfile
      context: ./API
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
      - proxy
    networks:
      - frontend
      - backend

  webapp:
    build: ./WebApp_Papeterie
    depends_on:
      - api_papeterie
    networks:
      - frontend

volumes:
  volume_papeterie:

networks:
  frontend:
  backend: